### ISSUE TITLE
Add c++ compilation tools

### ISSUE THREAD

**Issue by bokket** [xiyou-linuxer/Favorites#1]
Like [xmake](https://github.com/xmake-io/xmake/) and [bazel](https://github.com/bazelbuild/bazel)

**Comment by Y7n05h** [comment]
> Like [xmake](https://github.com/xmake-io/xmake/) and [bazel](https://github.com/bazelbuild/bazel)

Thank you for your participation in this project.
After separating the items related to the build tools into separate pages, I will merge them.
